# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ConnectionBoardcastor' do

  # Pods for ConnectionBoardcastor

  use_frameworks!
  pod 'ReachabilitySwift'

  target 'ConnectionBoardcastorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
